// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { DeleteFileFilesFilenameDeleteData, DeleteFileFilesFilenameDeleteErrors, DeleteFileFilesFilenameDeleteResponses, DownloadFileFilesFilenameGetData, DownloadFileFilesFilenameGetErrors, DownloadFileFilesFilenameGetResponses, ListFilesFilesListGetData, ListFilesFilesListGetResponses, SearchDefinitionBatchDefinitionBatchPostData, SearchDefinitionBatchDefinitionBatchPostErrors, SearchDefinitionBatchDefinitionBatchPostResponses, SearchDefinitionDefinitionPostData, SearchDefinitionDefinitionPostErrors, SearchDefinitionDefinitionPostResponses, SearchSearchBatchPostData, SearchSearchBatchPostErrors, SearchSearchBatchPostResponses, UploadFileFilesPostData, UploadFileFilesPostErrors, UploadFileFilesPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload File
 */
export const uploadFileFilesPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileFilesPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UploadFileFilesPostResponses, UploadFileFilesPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/files',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Delete File
 */
export const deleteFileFilesFilenameDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileFilesFilenameDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteFileFilesFilenameDeleteResponses, DeleteFileFilesFilenameDeleteErrors, ThrowOnError>({
        url: '/files/{filename}',
        ...options
    });
};

/**
 * Download File
 */
export const downloadFileFilesFilenameGet = <ThrowOnError extends boolean = false>(options: Options<DownloadFileFilesFilenameGetData, ThrowOnError>) => {
    return (options.client ?? client).get<DownloadFileFilesFilenameGetResponses, DownloadFileFilesFilenameGetErrors, ThrowOnError>({
        url: '/files/{filename}',
        ...options
    });
};

/**
 * List Files
 */
export const listFilesFilesListGet = <ThrowOnError extends boolean = false>(options?: Options<ListFilesFilesListGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListFilesFilesListGetResponses, unknown, ThrowOnError>({
        url: '/files/list/',
        ...options
    });
};

/**
 * Search Definition
 */
export const searchDefinitionDefinitionPost = <ThrowOnError extends boolean = false>(options: Options<SearchDefinitionDefinitionPostData, ThrowOnError>) => {
    return (options.client ?? client).post<SearchDefinitionDefinitionPostResponses, SearchDefinitionDefinitionPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/definition',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Search Definition Batch
 */
export const searchDefinitionBatchDefinitionBatchPost = <ThrowOnError extends boolean = false>(options: Options<SearchDefinitionBatchDefinitionBatchPostData, ThrowOnError>) => {
    return (options.client ?? client).post<SearchDefinitionBatchDefinitionBatchPostResponses, SearchDefinitionBatchDefinitionBatchPostErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/definition/batch',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Search
 */
export const searchSearchBatchPost = <ThrowOnError extends boolean = false>(options: Options<SearchSearchBatchPostData, ThrowOnError>) => {
    return (options.client ?? client).post<SearchSearchBatchPostResponses, SearchSearchBatchPostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/search/batch',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};
