// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_upload_file_files_post
 */
export type BodyUploadFileFilesPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type UploadFileFilesPostData = {
    body: BodyUploadFileFilesPost;
    path?: never;
    query?: never;
    url: '/files';
};

export type UploadFileFilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileFilesPostError = UploadFileFilesPostErrors[keyof UploadFileFilesPostErrors];

export type UploadFileFilesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteFileFilesFilenameDeleteData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type DeleteFileFilesFilenameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileFilesFilenameDeleteError = DeleteFileFilesFilenameDeleteErrors[keyof DeleteFileFilesFilenameDeleteErrors];

export type DeleteFileFilesFilenameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DownloadFileFilesFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type DownloadFileFilesFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadFileFilesFilenameGetError = DownloadFileFilesFilenameGetErrors[keyof DownloadFileFilesFilenameGetErrors];

export type DownloadFileFilesFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFilesFilesListGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/files/list/';
};

export type ListFilesFilesListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
